### ISSUE TITLE
Fails to get past Initialize screen with Ammo Percentage Indicator Extended

### ISSUE THREAD

**Issue by Benjutsu** [trumank/drg-mod-integration#44]
Mod: https://mod.io/g/drg/m/ammo-percentage-indicator-e
Mod works normally from mod.io

Using mod integration the game hangs at the Initialize screen forever.

**Comment by trumank** [comment]
The mod appears to be doing some strange things. There's a loop that just waits until the `UGCPackages` array (loaded mods) becomes non-empty and then once it is it looks for a particular mod ID and attempts to spawn an actor from it. Of course since the modding subsystem is disabled the array never populates so it just hangs. The mod ID it's looking for doesn't seem to even exist on mod.io so seems it's completely unnecessary. Here is a version with the loop patched out that appears to work to me.

[ammopercent_patched.zip](https://github.com/trumank/drg-mod-integration/files/12295817/ammopercent_patched.zip)
![wait loop](https://github.com/trumank/drg-mod-integration/assets/1144160/f374891f-97eb-4bb6-867b-f77e9a5a30e7)
