### ISSUE TITLE
pre-0.2.10 players cannot join hosts running 0.2.10

### ISSUE THREAD

**Issue by pH-JPEG** [trumank/drg-mod-integration#79]
Currently hosting with v0.2.10. Players that have not updated to v0.2.10 that attempt to join will receive the "Multiplayer Session Ended" message every time they attempt to join. Upon updating to v0.2.10, players can now join a v0.2.10 lobby.

Mod.io users can join without any issue.

**Comment by trumank** [comment]
Well it seems I've made a rather large blunder and broken backwards compatibility with previous versions. It's unfortunate the the resulting error message is completely useless in determining the root cause, but outdated versions were bound to have issues at some point so I think the best course of action is to commit to the breakage. We also have better update processes in place now so there should be fewer outdated clients out there in the future.
