### ISSUE TITLE
Marked lobbies?

### ISSUE THREAD

**Issue by meidoqt** [trumank/drg-mod-integration#85]
I was playing with mod-integration a few days ago and somebody mentioned my lobby is apparently marked as "modded". Couldn't find any info about this. Is this an undocumented feature, am I missing something? Would appreciate if someone could elaborate on why this is a thing.

**Comment by trumank** [comment]
That is correct: the integrator unconditionally prepends a "MODDED" label to the beginning of the lobby name (note: this does *not* tag the lobby like the official integration, it only changes the lobby name). The game itself still thinks it's entirely unmodded and there are no other restrictions in place.

I understand this is not ideal for players who are using only audio or visual mods. However, determining whether a lobby has gameplay affecting mods is challenging given the auto-verified mod category exists and that mods don't have to originate from mod.io in the first place.

Players hosting modded lobbies publicly for unsuspecting players to stumble into has been an issue ever since DRG mods first became a thing and I believe was one of the primary motivations behind GSG implementing an official modding system. Since this tool effectively lets anyone host a modded lobby publicly again, I've chosen to err on the side of caution by always labeling the lobby to hopefully prevent the tool from catching the attention of the devs. I may relax the restriction as I find time to refine detection of gameplay affecting mods in the future.
