### ISSUE TITLE
Using this seems to disable in-game volume control.

### ISSUE THREAD

**Issue by Tenome** [trumank/drg-mod-integration#89]
Any idea why? Adjusting the in-game volume doesn't work when I use this mod loader. Am I suppose to use an external configuration or something instead? Windows 10.

Here's my mod list, but I don't think any of them should affect the volume control.

https://pastebin.com/fQmDkNXU

Edit:
I found it. It seems to be the Shorter MC Ducking mod. It works on Mod.io, so it's something to do with how it's loaded here I think.

https://mod.io/g/drg/m/shorter-mc-callouts-x-no-mc-ducking#2059924

**Comment by trumank** [comment]
There's a similar mod that suffered the same issue that I patched previously: https://mod.io/g/drg/m/no-mission-control-ducking

The cause is some assets in the mod actually *failing* to properly load with the official integration. This means the mod is actually broken but because it's only in a half functional state, it just happens the issue doesn't occur with the official integration. Fixing it should just be a matter of downloading the mod and repackaging it to exclude the problematic assets

**Comment by Tenome** [comment]
Thanks for the quick reply, I'll try it out.
