### ISSUE TITLE
Removing [modded] tag?

### ISSUE THREAD

**Issue by biran4454** [trumank/drg-mod-integration#99]
Hey there, love the application, but I notice it prepends "[MODDED]" to my gameplay lobby.
I only play with verified mods for myself, so it's quite frustrating because people go in expecting fun mods and leave (sometimes mid-mission) when they find it's vanilla. Is there any cheap and easy fix for this, or would I have to fork and re-build the project?

**Comment by trumank** [comment]
I do not intend to support running without the lobby being tagged as modded as properly detecting when mods are not gameplay affecting is sufficiently annoying given the GSG's auto-verification system. It's not ideal but the lobby title having `[MODDED]` isn't a huge deal in my experience.

**Comment by StreetStrider** [comment]
@trumank Hi. All mods I'm using is Optional + Verified. As far as I understood, the combination of this two tags considered to be safe. I was using builtin mod.io integration for some time and my server hasn't been tagged as modded. I switched to drg-mod-integration and recently one of my teammates informed me that now my lobby description contains modded tag. It is not a super big deal, as you said, but it also not minuscule. I think a lot of users now would just skip my server because they would think it is a gameplay alteration server or they would fear of my mods corrupting their saves. But in fact the server is clean and I use only QoL on my client.

Can you consider implementing simple check that if all mods are Optional + Verified there should be no modded tag? It would be very helpful for me. So far this is the only issue I've faced, the overall experience was top class for me. This is how mod manager should be implemented, offline-first, explicit manual update policy. It is a good opposite of builting mod.io mess. It would be very painful for me to switch back.

**Comment by biran4454** [comment]
@StreetStrider Pretty sure this is unlikely to be officially added, but I'm sure you could fork the repo and remove the tag. Just make sure not to encourage doing this for servers with non-verified mods.

**Comment by StreetStrider** [comment]
@biran4454 yea, I've heard that it is a problem for manual mod installing, there is a lot of complaint about gameplay altering mods not being notified in any way. People on reddit speak about it once in a month.
To be clear, I'm asking for the opposite, so people with QoL mods would not be treated as gameplay modders.

**Comment by biran4454** [comment]
@StreetStrider I get what you're saying, I agree it's annoying when modded servers aren't labelled as such, and it's also a bit irksome that the modded tag shows up with only qol mods.
If you make a pull request for conditionally removing the tag, perhaps it'll be considered more strongly. Given this software is FOSS I wouldn't count on it being added by the maintainer though, they have enough on their hands.

**Comment by StreetStrider** [comment]
@trumank is it possible to install mods with drg-mod-integration then remove integration but preserve installed mods? I see that as a viable workaround for me, because I'm now actively looking for my mods' updates. But I don't know is it possible to achieve with drg-mod-integration. It seemes to have a sort of hook which disables mod.io and adds this modded tag, so I'm not sure how this workaround idea apply.
